[files]
extend-exclude = ["package.json", "package-lock.json"]
[default.extend-identifiers]
"HashiCorp" = "HashiCorp"
"HashiStack" = "HashiStack"
"TietoEVRY" = "TietoEVRY"
"UE4" = "UE4"
"CAF" = "CAF"
"MENA" = "MENA"

[default.extend-words]
"AKS" = "AKS"
"Abou" = "Abou"
"Hach" = "Hach"
